In [ ]:
import pandas as pd


In [ ]:
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv"


In [ ]:
df = pd.read_csv(dataset_url)


In [ ]:
df.head()


   Respondent  ...                  SurveyEase
0           4  ...                        Easy
1           9  ...  Neither easy nor difficult
2          13  ...                        Easy
3          16  ...  Neither easy nor difficult
4          17  ...                        Easy

[5 rows x 85 columns]


In [ ]:
print(len(df))


11552


In [ ]:
print(len(df.columns))


85


In [ ]:
print(df.dtypes)


Respondent       int64
MainBranch      object
Hobbyist        object
OpenSourcer     object
OpenSource      object
                 ...  
Sexuality       object
Ethnicity       object
Dependents      object
SurveyLength    object
SurveyEase      object
Length: 85, dtype: object


In [ ]:
mean_age = df['Age'].mean()


In [ ]:
print(mean_age)


30.77239449133718


In [ ]:
unique_countries = df['Country'].nunique()


In [ ]:
print(unique_countries)


135


In [ ]:
duplicates = df[df.duplicated()]


In [ ]:
print(duplicates)


      Respondent  ...                  SurveyEase
1168        2339  ...                        Easy
1169        2342  ...                        Easy
1170        2343  ...  Neither easy nor difficult
1171        2344  ...                        Easy
1172        2347  ...                        Easy
...          ...  ...                         ...
2297        4674  ...  Neither easy nor difficult
2298        4675  ...                        Easy
2299        4676  ...                        Easy
2300        4677  ...                        Easy
2301        4679  ...                        Easy

[154 rows x 85 columns]


In [ ]:
df.drop_duplicates(inplace=True)


In [ ]:
df.to_csv('cleaned_data.csv', index=False)


In [ ]:
print(len(df))


11398


In [ ]:
print(len(df.columns))


85


In [ ]:
missing_values = df.isnull().sum()


In [ ]:
print(missing_values)


Respondent        0
MainBranch        0
Hobbyist          0
OpenSourcer       0
OpenSource       81
               ... 
Sexuality       542
Ethnicity       675
Dependents      140
SurveyLength     19
SurveyEase       14
Length: 85, dtype: int64


In [ ]:
missing_values_workloc = df['WorkLoc'].isnull().sum()


In [ ]:
print(missing_values_workloc)


32


In [ ]:
workloc_value_counts = df['WorkLoc'].value_counts()


In [ ]:
print(workloc_value_counts)


WorkLoc
Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: count, dtype: int64


In [ ]:
df['WorkLoc'].fillna('Office', inplace = True)


In [ ]:
unique_compfreq = df['CompFreq'].unique()


In [ ]:
print(unique_compfreq)


['Yearly' 'Monthly' 'Weekly' nan]


In [ ]:
def normalize_compensation(row):
    if row['CompFreq'] == 'Yearly':
        return row['CompTotal']
    elif row['CompFreq'] == 'Monthly':
        return row['CompTotal'] * 12
    elif row['CompFreq'] == 'Weekly':
        return row['CompTotal'] * 52



In [ ]:
df['NormalizedAnnualCompensation'] = df.apply(normalize_compensation, axis=1)


In [ ]:
import seaborn as sns


In [ ]:
import matplotlib.pyplot as plt


In [ ]:
import matplotlib


In [ ]:
matplotlib.use('Agg')


In [ ]:
sns.displot(df['ConvertedComp'], kde = True)


In [ ]:
plt.title('Distrubution of Annual Salaries')


Text(0.5, 1.0, 'Distrubution of Annual Salaries')


In [ ]:
plt.xlabel('Annual Salary')


Text(0.5, 9.444444444444438, 'Annual Salary')


In [ ]:
plt.ylabel('Frequency')


Text(5.069444444444445, 0.5, 'Frequency')


In [ ]:
plt.ticklabel_format(style='plain', axis='x')


In [ ]:
plt.xticks(rotation=90)


(array([-250000.,       0.,  250000.,  500000.,  750000., 1000000.,
       1250000., 1500000., 1750000., 2000000., 2250000.]), [Text(-250000.0, 0, '−250000'), Text(0.0, 0, '0'), Text(250000.0, 0, '250000'), Text(500000.0, 0, '500000'), Text(750000.0, 0, '750000'), Text(1000000.0, 0, '1000000'), Text(1250000.0, 0, '1250000'), Text(1500000.0, 0, '1500000'), Text(1750000.0, 0, '1750000'), Text(2000000.0, 0, '2000000'), Text(2250000.0, 0, '2250000')])


In [ ]:
plt.tight_layout()


In [ ]:
plt.savefig('annual_salary_distribution_plot.png', bbox_inches='tight')


In [ ]:
plt.show()


In [ ]:
plt.hist(df['ConvertedComp'], bins=10, edgecolor='black')


(array([9659.,  238.,  115.,  125.,   99.,  131.,   34.,   15.,   15.,
        151.]), array([      0.,  200000.,  400000.,  600000.,  800000., 1000000.,
       1200000., 1400000., 1600000., 1800000., 2000000.]), <BarContainer object of 10 artists>)


In [ ]:
plt.title('Histogram of Annual Compensation')


Text(0.5, 1.0, 'Histogram of Annual Compensation')


In [ ]:
plt.xlabel('Annual Salary')


Text(0.5, 29.00000000000003, 'Annual Salary')


In [ ]:
plt.ylabel('Frequency')


Text(29.0, 0.5, 'Frequency')


In [ ]:
plt.ticklabel_format(style='plain', axis='x')


In [ ]:
plt.xticks(rotation=90)


(array([-250000.,       0.,  250000.,  500000.,  750000., 1000000.,
       1250000., 1500000., 1750000., 2000000., 2250000.]), [Text(-250000.0, 0, '−250000'), Text(0.0, 0, '0'), Text(250000.0, 0, '250000'), Text(500000.0, 0, '500000'), Text(750000.0, 0, '750000'), Text(1000000.0, 0, '1000000'), Text(1250000.0, 0, '1250000'), Text(1500000.0, 0, '1500000'), Text(1750000.0, 0, '1750000'), Text(2000000.0, 0, '2000000'), Text(2250000.0, 0, '2250000')])


In [ ]:
plt.tight_layout()


In [ ]:
plt.savefig('annual_salary_histogram.png', bbox_inches='tight')


In [ ]:
plt.show()


In [ ]:
converted_comp_median = df['ConvertedComp'].median()


In [ ]:
print(converted_comp_median)


57745.0


In [ ]:
count_man = df[df['Gender'] == 'Man'].shape[0]


In [ ]:
print(count_man)


10480


In [ ]:
woman_data = df[df['Gender'] == 'Woman']


In [ ]:
median_converted_comp_women = woman_data['ConvertedComp'].median()


In [ ]:
print(median_converted_comp_women)


57708.0


In [ ]:
age_summary = df['Age'].describe()


In [ ]:
print(age_summary)


count    11111.000000
mean        30.778895
std          7.393686
min         16.000000
25%         25.000000
50%         29.000000
75%         35.000000
max         99.000000
Name: Age, dtype: float64


In [ ]:
plt.figure()


Figure(640x480)


In [ ]:
plt.hist(df['Age'], bins=10, edgecolor='Red')


(array([2.094e+03, 5.337e+03, 2.557e+03, 8.420e+02, 2.250e+02, 4.900e+01,
       6.000e+00, 0.000e+00, 0.000e+00, 1.000e+00]), array([16. , 24.3, 32.6, 40.9, 49.2, 57.5, 65.8, 74.1, 82.4, 90.7, 99. ]), <BarContainer object of 10 artists>)


In [ ]:
plt.title('Histogram of Age of Participants')


Text(0.5, 1.0, 'Histogram of Age of Participants')


In [ ]:
plt.xlabel('Age')


Text(0.5, 0, 'Age')


In [ ]:
plt.ylabel('Frequency')


Text(0, 0.5, 'Frequency')


In [ ]:
plt.ticklabel_format(style='plain', axis='x')


In [ ]:
plt.xticks(rotation=90)


(array([  0.,  20.,  40.,  60.,  80., 100., 120.]), [Text(0.0, 0, '0'), Text(20.0, 0, '20'), Text(40.0, 0, '40'), Text(60.0, 0, '60'), Text(80.0, 0, '80'), Text(100.0, 0, '100'), Text(120.0, 0, '120')])


In [ ]:
plt.tight_layout()


In [ ]:
plt.savefig('histogram_age.png', bbox_inches='tight')


In [ ]:
plt.show()


In [ ]:
plt.figure(figsize=(10, 6))


Figure(1000x600)


In [ ]:
sns.boxplot(x=df['ConvertedComp'])


Axes(0.125,0.11;0.775x0.77)


In [ ]:
plt.title('Box Plot of Converted Compensation')


Text(0.5, 1.0, 'Box Plot of Converted Compensation')


In [ ]:
plt.xlabel('Converted Compensation')


Text(0.5, 0, 'Converted Compensation')


In [ ]:
plt.ticklabel_format(style='plain', axis='x')


In [ ]:
plt.xticks(rotation=90)


(array([-250000.,       0.,  250000.,  500000.,  750000., 1000000.,
       1250000., 1500000., 1750000., 2000000., 2250000.]), [Text(-250000.0, 0, '−250000'), Text(0.0, 0, '0'), Text(250000.0, 0, '250000'), Text(500000.0, 0, '500000'), Text(750000.0, 0, '750000'), Text(1000000.0, 0, '1000000'), Text(1250000.0, 0, '1250000'), Text(1500000.0, 0, '1500000'), Text(1750000.0, 0, '1750000'), Text(2000000.0, 0, '2000000'), Text(2250000.0, 0, '2250000')])


In [ ]:
plt.tight_layout()


In [ ]:
plt.savefig('Coverted_Comp_box_plot.png', bbox_inches='tight')


In [ ]:
plt.show()


In [ ]:
Q1 = df['ConvertedComp'].quantile(0.25)


In [ ]:
Q3 = df['ConvertedComp'].quantile(0.75)


In [ ]:
IQR = Q3 - Q1


In [ ]:
print(IQR)


73132.0


In [ ]:
lower_bound = Q1 - 1.5 * IQR


In [ ]:
print(lower_bound)


-82830.0


In [ ]:
upper_bound = Q3 + 1.5 * IQR


In [ ]:
print(upper_bound)


209698.0


In [ ]:
outliers = df[(df['ConvertedComp'] < lower_bound) | (df['ConvertedComp'] > upper_bound)]


In [ ]:
number_outliers = outliers.shape[0]


In [ ]:
print(number_outliers)


879


In [ ]:
new_data = df[(df['ConvertedComp'] >= lower_bound) & (df['ConvertedComp'] <= upper_bound)]


In [ ]:
new_data.to_csv('no_outliers_data.csv', index=False)


In [ ]:
numeric_data = new_data.select_dtypes(include=['number'])


In [ ]:
correlation_matrix = numeric_data.corr()


In [ ]:
age_correlation = correlation_matrix['Age']


In [ ]:
print(age_correlation)


Respondent                      0.002180
CompTotal                       0.006337
ConvertedComp                   0.401821
WorkWeekHrs                     0.032032
CodeRevHrs                     -0.012878
Age                             1.000000
NormalizedAnnualCompensation   -0.016299
Name: Age, dtype: float64


In [ ]:
deprecated

Traceback (most recent call last):
  File "c:\Users\USER-PC\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
NameError: name 'deprecated' is not defined



In [ ]:
deprecated

Traceback (most recent call last):
  File "c:\Users\USER-PC\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
NameError: name 'deprecated' is not defined



In [ ]:
import sqlite3


In [ ]:
conn = sqlite3.connect("m4_survey_data.sqlite")


In [ ]:
from sqlalchemy import create_engine


In [ ]:
engine = create_engine('sqlite:///m4_survey_data.sqlite')


In [ ]:
query = "SELECT ConvertedComp FROM survey_data"


In [ ]:
cursor = conn.cursor()


In [ ]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")


In [ ]:
tables = cursor.fetchall()


In [ ]:
print("Tables in the database:", tables)


Tables in the database: []


In [ ]:
import requests


In [ ]:
url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m4_survey_data.sqlite'


In [ ]:
response = requests.get(url)


In [ ]:
with open('m4_survey_data.sqlite', 'wb') as file:
    file.write(response.content)



In [ ]:
if response.status_code == 200: 
    with open('m4_survey_data.sqlite', 'wb') as file: 
        file.write(response.content) 
    print("File downloaded successfully!") 
else: 
    print(f"Failed to download file. Status code: {response.status_code}")



File downloaded successfully!


In [ ]:
engine = create_engine('sqlite:///m4_survey_data.sqlite')


In [ ]:
query = "SELECT ConvertedComp FROM survey_data"


In [ ]:
data = pd.read_sql(query, engine)


Traceback (most recent call last):
  File "c:\Users\USER-PC\Desktop\Code Folder\Data Analysis Certificate Project\.venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\USER-PC\Desktop\Code Folder\Data Analysis Certificate Project\.venv\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: survey_data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\USER-PC\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string

In [ ]:
cursor = conn.cursor()


In [ ]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")


In [ ]:
tables = cursor.fetchall()


In [ ]:
print("Tables in the database:", tables)


Tables in the database: [('EduOther',), ('DevType',), ('LastInt',), ('JobFactors',), ('WorkPlan',), ('WorkChallenge',), ('LanguageWorkedWith',), ('LanguageDesireNextYear',), ('DatabaseWorkedWith',), ('DatabaseDesireNextYear',), ('PlatformWorkedWith',), ('PlatformDesireNextYear',), ('WebFrameWorkedWith',), ('WebFrameDesireNextYear',), ('MiscTechWorkedWith',), ('MiscTechDesireNextYear',), ('DevEnviron',), ('Containers',), ('SOVisitTo',), ('SONewContent',), ('Gender',), ('Sexuality',), ('Ethnicity',), ('master',)]


In [ ]:
conn.close()


In [ ]:
deprecated

Traceback (most recent call last):
  File "c:\Users\USER-PC\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
NameError: name 'deprecated' is not defined



In [ ]:
def list_columns(table_name):
    cursor.execute(f"PRAGMA table_info({table_name})")
    columns = cursor.fetchall()
    print(f"Columns in {table_name}:", [column[1] for column in columns])



In [ ]:
def list_columns(master):
    cursor.execute(f"PRAGMA table_info({master})")



In [ ]:
engine = create_engine('sqlite:///m4_survey_data.sqlite')


In [ ]:
query = "SELECT ConvertedComp FROM master"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
data = data.dropna()


In [ ]:
plt.figure(figsize=(10, 6))


Figure(1000x600)


In [ ]:
plt.hist(data['ConvertedComp'], bins=30, edgecolor='black')


(array([6.008e+03, 2.988e+03, 6.630e+02, 1.440e+02, 5.100e+01, 4.300e+01,
       4.400e+01, 3.100e+01, 4.000e+01, 5.300e+01, 3.600e+01, 3.600e+01,
       4.300e+01, 1.300e+01, 1.480e+02, 4.000e+00, 1.100e+01, 1.100e+01,
       1.600e+01, 1.400e+01, 4.000e+00, 9.000e+00, 1.000e+00, 5.000e+00,
       5.000e+00, 6.000e+00, 9.000e+00, 7.000e+00, 0.000e+00, 1.390e+02]), array([      0.        ,   66666.66666667,  133333.33333333,
        200000.        ,  266666.66666667,  333333.33333333,
        400000.        ,  466666.66666667,  533333.33333333,
        600000.        ,  666666.66666667,  733333.33333333,
        800000.        ,  866666.66666667,  933333.33333333,
       1000000.        , 1066666.66666667, 1133333.33333333,
       1200000.        , 1266666.66666667, 1333333.33333333,
       1400000.        , 1466666.66666667, 1533333.33333333,
       1600000.        , 1666666.66666667, 1733333.33333333,
       1800000.        , 1866666.66666667, 1933333.33333333,
       2000000.       

In [ ]:
plt.title('Histogram of Converted Compensation')


Text(0.5, 1.0, 'Histogram of Converted Compensation')


In [ ]:
plt.xlabel('Converted Compensation')


Text(0.5, 0, 'Converted Compensation')


In [ ]:
plt.ylabel('Frequency')


Text(0, 0.5, 'Frequency')


In [ ]:
plt.ticklabel_format(style='plain', axis='x')


In [ ]:
plt.savefig('sqldatabase_convertedcomp_histogram.png')


In [ ]:
plt.show()


In [ ]:
query = "SELECT Age FROM master"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
data = data.dropna()


In [ ]:
plt.figure(figsize=(10, 6))


Figure(1000x600)


In [ ]:
sns.boxplot(x=data['Age'])


Axes(0.125,0.11;0.775x0.77)


In [ ]:
plt.title('Box Plot of Age')


Text(0.5, 1.0, 'Box Plot of Age')


In [ ]:
plt.xlabel('Age')


Text(0.5, 0, 'Age')


In [ ]:
plt.savefig('sqldatabase_age_boxplot.png')


In [ ]:
plt.show()


In [ ]:
query = "SELECT Age, WorkWeekHrs FROM master"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
data = data.dropna()


In [ ]:
plt.figure(figsize=(10, 6))


Figure(1000x600)


In [ ]:
sns.scatterplot(x=data['Age'], y=data['WorkWeekHrs'])


Axes(0.125,0.11;0.775x0.77)


In [ ]:
plt.title('Scatter Plot of Age vs. Work Week Hours')


Text(0.5, 1.0, 'Scatter Plot of Age vs. Work Week Hours')


In [ ]:
plt.xlabel('Age')


Text(0.5, 0, 'Age')


In [ ]:
plt.ylabel('Work Week Hours')


Text(0, 0.5, 'Work Week Hours')


In [ ]:
plt.savefig('sqldatabase_age_workweekhrs_scatter.png')


In [ ]:
plt.show()


In [ ]:
query = "SELECT Age, WorkWeekHrs, CodeRevHrs FROM master"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
data = data.dropna()


In [ ]:
norm = (data['Age'] - data['Age'].min()) / (data['Age'].max() - data['Age'].min())


In [ ]:
plt.figure(figsize=(12, 8))


Figure(1200x800)


In [ ]:
bubble_plot = sns.scatterplot(
    x=data['WorkWeekHrs'],
    y=data['CodeRevHrs'],
    size=norm,
    sizes=(20, 200),
    hue=data['Age'],
    palette='viridis',
    legend=False,
    alpha=0.6
)



In [ ]:
plt.title('Bubble Plot of Work Week Hours vs. Code Review Hours')


Text(0.5, 1.0, 'Bubble Plot of Work Week Hours vs. Code Review Hours')


In [ ]:
plt.xlabel('Work Week Hours')


Text(0.5, 0, 'Work Week Hours')


In [ ]:
plt.ylabel('Code Rev Hours')


Text(0, 0.5, 'Code Rev Hours')


In [ ]:
plt.savefig('sqldatabase_workweekhrs_coderevhrs_bubble.png')


In [ ]:
plt.show()


In [ ]:
query = "SELECT DatabaseDesireNextYear FROM DatabaseDesireNextYear"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
data['DatabaseDesireNextYear'] = data['DatabaseDesireNextYear'].str.split(';')


In [ ]:
all_databases = data.explode('DatabaseDesireNextYear')['DatabaseDesireNextYear'].value_counts()


In [ ]:
top_5_databases = all_databases.head(5)


In [ ]:
plt.clf()


In [ ]:
plt.figure(figsize=(10, 7))


Figure(1000x700)


In [ ]:
plt.pie(
    top_5_databases,
    labels=top_5_databases.index,
    autopct='%1.1f%%',
    startangle=140,
    colors=sns.color_palette('viridis', len(top_5_databases))
)



([<matplotlib.patches.Wedge object at 0x000002383539B9D0>, <matplotlib.patches.Wedge object at 0x000002383539BD90>, <matplotlib.patches.Wedge object at 0x000002383676C190>, <matplotlib.patches.Wedge object at 0x000002383676C550>, <matplotlib.patches.Wedge object at 0x000002383676C910>], [Text(-1.09636857940642, -0.08930810764062207, 'PostgreSQL'), Text(-0.05824543048113747, -1.098456858428253, 'MongoDB'), Text(1.0268380064784501, -0.3944663590870109, 'Redis'), Text(0.7472595076539573, 0.807219442419944, 'MySQL'), Text(-0.38579279513177245, 1.0301281081615115, 'Elasticsearch')], [Text(-0.5980192251307744, -0.04871351325852113, '24.8%'), Text(-0.03177023480789316, -0.5991582864154107, '20.9%'), Text(0.5600934580791546, -0.215163468592915, '19.1%'), Text(0.40759609508397665, 0.44030151404724216, '18.8%'), Text(-0.2104324337082395, 0.561888058997188, '16.4%')])


In [ ]:
plt.title('Top 5 Databases Respondents Wish to Learn Next Year')


Text(0.5, 1.0, 'Top 5 Databases Respondents Wish to Learn Next Year')


In [ ]:
plt.axis('equal')


(np.float64(-1.0999982640655108), np.float64(1.0999947805766306), np.float64(-1.0999996762476416), np.float64(1.0999985100223448))


In [ ]:
plt.savefig('sqldatabase_desired_database_pie.png')


In [ ]:
plt.show()


In [ ]:
query = "SELECT Age, WorkWeekHrs, CodeRevHrs FROM master"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
age_group = data[(data['Age'] >= 30) & (data['Age'] <= 35)]


In [ ]:
median_workweek_hrs = age_group['WorkWeekHrs'].median()


In [ ]:
median_coderev_hrs = age_group['CodeRevHrs'].median()


In [ ]:
median_values = pd.DataFrame({
    'Category': ['WorkWeekHrs', 'CodeRevHrs'],
    'Median Hours': [median_workweek_hrs, median_coderev_hrs]
})



In [ ]:
plt.clf()


In [ ]:
plt.figure(figsize=(10, 6))


Figure(1000x600)


In [ ]:
plt.bar(median_values['Category'], median_values['Median Hours'], color=['#1f77b4', '#ff7f0e'])


<BarContainer object of 2 artists>


In [ ]:
plt.title('Median WorkWeekHrs and CodeRevHrs for Age Group 30-35')


Text(0.5, 1.0, 'Median WorkWeekHrs and CodeRevHrs for Age Group 30-35')


In [ ]:
plt.xlabel('Category')


Text(0.5, 0, 'Category')


In [ ]:
plt.ylabel('Median Hours')


Text(0, 0.5, 'Median Hours')


In [ ]:
plt.savefig('sqldatabase_workweekhrs_coderevhrs-median_stacked.png')


In [ ]:
plt.show()


In [ ]:
query = "SELECT Age, ConvertedComp FROM master"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
age_filtered_data = data[(data['Age'] >= 45) & (data['Age'] <= 60)]


In [ ]:
median_converted_comp = age_filtered_data.groupby('Age')['ConvertedComp'].median()


In [ ]:
plt.clf()


In [ ]:
plt.figure(figsize=(12, 8))


Figure(1200x800)


In [ ]:
plt.plot(median_converted_comp.index, median_converted_comp.values, marker='o')


In [ ]:
plt.title('Median Converted Compensation for Ages 45 to 60')


Text(0.5, 1.0, 'Median Converted Compensation for Ages 45 to 60')


In [ ]:
plt.xlabel('Age')


Text(0.5, 0, 'Age')


In [ ]:
plt.ylabel('Median Converted Compensation')


Text(0, 0.5, 'Median Converted Compensation')


In [ ]:
plt.grid(True)


In [ ]:
plt.savefig('sqldatabase_media_convertedcomp_line.png')


In [ ]:
plt.show()


In [ ]:
query = "SELECT MainBranch FROM master"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
main_branch_counts = data['MainBranch'].value_counts()


In [ ]:
plt.clf()


In [ ]:
plt.figure(figsize=(12, 8))


Figure(1200x800)


In [ ]:
main_branch_counts.plot(kind='barh', color='blue')


Axes(0.125,0.11;0.775x0.77)


In [ ]:
plt.title('Distribution of Main Branches')


Text(0.5, 1.0, 'Distribution of Main Branches')


In [ ]:
plt.xlabel('Count')


Text(0.5, 0, 'Count')


In [ ]:
plt.ylabel('Main Branch')


Text(0, 0.5, 'Main Branch')


In [ ]:
plt.tight_layout()


In [ ]:
plt.savefig('sqldatabase_mainbranch_bar.png')


In [ ]:
plt.show()


In [ ]:
conn.close()


In [ ]:
url = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m4_survey_data.sqlite'


In [ ]:
response = requests.get(url)


In [ ]:
if response.status_code == 200: 
    with open('m4_survey_data.sqlite', 'wb') as file: 
        file.write(response.content) 
    print("File downloaded successfully!") 
else: 
    print(f"Failed to download file. Status code: {response.status_code}")



File downloaded successfully!


In [ ]:
engine = create_engine('sqlite:///m4_survey_data.sqlite')


In [ ]:
deprecated

Traceback (most recent call last):
  File "c:\Users\USER-PC\.vscode\extensions\ms-python.python-2024.18.0-win32-x64\python_files\python_server.py", line 130, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 1, in <module>
NameError: name 'deprecated' is not defined



In [ ]:
engine = create_engine('sqlite:///m4_survey_data.sqlite')


In [ ]:
query = """
SELECT COUNT(*) as sql_users_count
FROM LanguageWorkedWith
WHERE LanguageWorkedWith LIKE '%SQL%'
"""



In [ ]:
result = pd.read_sql(query, engine)


In [ ]:
sql_users_count = result['sql_users_count'].iloc[0]


In [ ]:
print(sql_users_count)


7106


In [ ]:
query = "SELECT LanguageDesireNextYear FROM LanguageDesireNextYear"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
data['LanguageDesireNextYear'] = data['LanguageDesireNextYear'].str.split(';')


In [ ]:
all_languages = data.explode('LanguageDesireNextYear')['LanguageDesireNextYear'].value_counts()


In [ ]:
python_rank = all_languages.reset_index().reset_index()


In [ ]:
python_rank.columns = ['Rank', 'Language', 'Count']


In [ ]:
python_rank = python_rank[python_rank['Language'] == 'Python'].iloc[0]['Rank'] + 1


In [ ]:
print(python_rank)


3


In [ ]:
query = "SELECT LanguageWorkedWith FROM LanguageWorkedWith"


In [ ]:
data = pd.read_sql(query, engine)


In [ ]:
mysql_only = data[data['LanguageWorkedWith'].str.strip() == 'MySQL']


In [ ]:
mysql_only_count = mysql_only.shape[0]


In [ ]:
print(mysql_only_count)


0
